### ISSUE TITLE
Domain registration expiry: resourcereasoning.com

### ISSUE THREAD

**Issue by td202** [resource-reasoning/resourcereasoning.com#3]
The domain name registration for resourcereasoning.com expires on 21st January 2016.  After that time, if nothing is done to renew it, the website will no longer be accessible at that address.  There are a few possible choices for how to proceed:
- Allow the domain to expire.
- I renew the domain.
- I transfer the domain to someone else who can then renew it.

Please let me know which option is preferred.

**Comment by edgemaster** [comment]
Domain has been renewed for a year and transferred into my name.

**Comment by philippagardner** [comment]
Thank you! P

Sent from my iPhone

On 18 Jan 2016, at 13:15, Thomas Wood <notifications@github.com<mailto:notifications@github.com>> wrote:


Domain has been renewed for a year and transferred into my name.

-
